package com.resources;

import com.model.RoleInfo;

// @author: ragrahari

rule "New Year adhoc"
	no-loop true
	ruleflow-group "adhoc"
	date-effective "30-Dec-2019"
	date-expires "02-Jan-2020"
	dialect "mvel"
	when
		r : RoleInfo( role == "compute" )
	then
	    modify(r){setRoleTargetCapacity(1 + r.getRoleTargetCapacity())}
		System.out.println("Fired AdHoc for compute");
end

rule "Row 1 adhoc"
	no-loop true
	ruleflow-group "adhoc"
	date-effective "13-Mar-2019"
	date-expires "30-Sep-2019"
	dialect "mvel"
	when
		r : RoleInfo( role == "compute" )
	then
	    modify(r){setRoleTargetCapacity(1 + r.getRoleTargetCapacity())}
		System.out.println("Fired AdHoc for compute");
end

rule "Row 2 adhoc"
	no-loop true
	ruleflow-group "adhoc"
	date-effective "10-Aug-2019"
	date-expires "30-Aug-2019"
	dialect "mvel"
	when
		r : RoleInfo( role == "web" )
	then
		modify(r){setRoleTargetCapacity(2 + r.getRoleTargetCapacity())}
		System.out.println("Fired AdHoc for web");
end

rule "Row 3 adhoc"
	no-loop true
	ruleflow-group "adhoc"
	date-effective "30-Sep-2018"
	date-expires "30-Nov-2018"
	dialect "mvel"
	when
		r : RoleInfo( role == "operations" )
	then
		modify(r){setRoleTargetCapacity(3 + r.getRoleTargetCapacity())}
		System.out.println("Fired AdHoc for operations");
end
