//created on: Sep 27, 2018
package com.resources;

import com.model.RoleInfo;

// @author: ragrahari

rule "gradualScaleUp"
	dialect "mvel"
	no-loop true
	ruleflow-group "performance"
	when
		r : RoleInfo( r.getFlatPerformanceInfo().getCpu() > 85 || r.getFlatPerformanceInfo().getMemory() > 85)
	then
		modify( r ) {
				setRoleTargetCapacity( r.getRoleTargetCapacity()+1 )
		}
		System.out.println("Gradual scale up by 1");
end

rule "gradualScaleDown"
	dialect "mvel"
	no-loop true
	ruleflow-group "performance"
	when
		r : RoleInfo( r.getFlatPerformanceInfo().getCpu() < 15 && r.getFlatPerformanceInfo().getMemory() < 15)
	then
		modify( r ) {
				setRoleTargetCapacity( r.getRoleTargetCapacity()-1 )
		}
		System.out.println("Gradual scale down by 1");
end
